version: '3.8'
services:
  mongoDb:
    image: mongo:5
    container_name: mongo-ms-auth
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGODB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - /mongo:/data/db
    networks:
      - ms-auth-network

  ms-auth:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    ports:
      - ${APP_PORT}:8080
    restart: always
    env_file: ".env"
    depends_on:
      - mongoDb
    container_name: ms-auth-container
    networks:
      - ms-auth-network

networks:
  ms-auth-network:
    driver: bridge