version: '3.8'

services:
  mongoDb:
    image: mongo:5
    container_name: mongodb-container
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - /mongo:/data/db
    networks:
      - ms-auth-network
    command:
      - --auth

  ms-auth:
    build:
      context: .
      target: $STAGE
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      #- /app/.gradle
    ports:
      - $APP_PORT:8080
    restart: always
    env_file: ".env"
    depends_on:
      - mongoDb
    container_name: springboot-container
    networks:
      - ms-auth-network

networks:
  ms-auth-network:
    driver: bridge